---
- hosts: all
  tasks:
    - name: Check the disk images size of hosts
      shell: df -TH
      register: diskoutput

    - debug: var=diskoutput

    - name: check the /data size
      shell: df -TH | grep "/data" | awk '{print $6}' | sed 's/%//'
      register: dataout

    - debug: var=dataout

    - name: check vg size
      shell: vgs | awk '{print $7}'| sed -sn 2p | sed 's/<//g'
      register: vgcheck

    - debug: var=vgcheck.stdout  

    - name: check the free vg size
      shell: vgs | awk '{print $7}'| sed -sn 2p | sed 's/<//g' | sed 's/g//g'
      register: vgsout

    - debug: var=vgsout

#   - name: Check the size and extend the size accordingly
#     shell: lvextend -r -L 1G -n /dev/centos/data
#     when: dataout.stdout >= 6 and vgOutput >= size available
#     register: lvextend
#
#   - debug: var=lvextend
#   - name: sending Email
#     mail:
#     host: smtp.redhat.com
#     port: 587
#     from: noreply@redhat.com
#     to: "{{ email_id }}"
#     subject: Slash partition alert on "{{ inventory_hostname }}"
#     body: |
#      Hello Team,
#       We have received the notification for slash partition on {{ inventory_hostname }} host. Total Disk Utilization is has crossed {{ disk_status.stdout }}%.
#       Output Before executing Playbook:
#       {{ before.stdout }}
#       Output After executing Playbook:
#       {{ after.stdout }}
#                                   
#       We have perform basic clean-up steps following doc "https://mojo.redhat.com/docs/DOC-925160" to resolve the alert.
#       Regards,
#       GES Team
#     when: (disk_status.stdout >= "90")
#     delegate_to: localhost
#     ignore_errors: yes
#
